const SYSTEM_ROLES = {
  ADMIN: 'admin',
  VIEN_TRUONG: 'vien_truong',
  TRUONG_LAB: 'truong_lab',
  LEADER: 'leader',
  MEMBER: 'member',
  GUEST: 'guest',
};

const SYSTEM_ROLE_VALUES = Object.values(SYSTEM_ROLES);

const USER_STATUS = {
  PENDING: 'pending',
  ACTIVE: 'active',
  REJECTED: 'rejected',
  LOCKED: 'locked',
};

const USER_STATUS_VALUES = Object.values(USER_STATUS);

const APPROVAL_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
};

const APPROVAL_STATUS_VALUES = Object.values(APPROVAL_STATUS);

const AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  APPROVAL_CREATED: 'APPROVAL_CREATED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_STATUS_CHANGED: 'PROJECT_STATUS_CHANGED',
  PROJECT_MEMBER_ADDED: 'PROJECT_MEMBER_ADDED',
  PROJECT_MEMBER_REMOVED: 'PROJECT_MEMBER_REMOVED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  MILESTONE_CREATED: 'MILESTONE_CREATED',
  MILESTONE_UPDATED: 'MILESTONE_UPDATED',
};

const PROJECT_STATUS = {
  PLANNING: 'planning',
  ACTIVE: 'active',
  PAUSED: 'paused',
  DONE: 'done',
  ARCHIVED: 'archived',
};

const PROJECT_STATUS_VALUES = Object.values(PROJECT_STATUS);

const PROJECT_TAGS = {
  AI_ML: 'AI/ML',
  FPGA: 'FPGA',
  ROBOTICS: 'Robotics',
  EMBEDDED: 'Embedded',
  DSP: 'DSP',
  IOT: 'IoT',
  OTHER: 'Other',
};

const PROJECT_TAG_VALUES = Object.values(PROJECT_TAGS);

const PROJECT_ROLES = {
  LEADER: 'leader',
  MEMBER: 'member',
};

const PROJECT_ROLE_VALUES = Object.values(PROJECT_ROLES);

const TASK_STATUS = {
  TODO: 'todo',
  IN_PROGRESS: 'in_progress',
  REVIEW: 'review',
  DONE: 'done',
};

const TASK_STATUS_VALUES = Object.values(TASK_STATUS);

const TASK_PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  URGENT: 'urgent',
};

const TASK_PRIORITY_VALUES = Object.values(TASK_PRIORITY);

const REPORT_STATUS = {
  SUBMITTED: 'submitted',
  LATE: 'late',
  MISSING: 'missing',
};

const REPORT_STATUS_VALUES = Object.values(REPORT_STATUS);

const GIT_PROVIDERS = {
  GITHUB: 'github',
  GITLAB: 'gitlab',
  BITBUCKET: 'bitbucket',
};

const GIT_PROVIDER_VALUES = Object.values(GIT_PROVIDERS);

const GIT_VISIBILITY = {
  PRIVATE: 'private',
  PUBLIC: 'public',
  INTERNAL: 'internal',
};

const GIT_VISIBILITY_VALUES = Object.values(GIT_VISIBILITY);

// Valid project status transitions
const PROJECT_STATUS_TRANSITIONS = {
  [PROJECT_STATUS.PLANNING]: [PROJECT_STATUS.ACTIVE],
  [PROJECT_STATUS.ACTIVE]: [PROJECT_STATUS.PAUSED, PROJECT_STATUS.DONE],
  [PROJECT_STATUS.PAUSED]: [PROJECT_STATUS.ACTIVE],
  [PROJECT_STATUS.DONE]: [PROJECT_STATUS.ARCHIVED],
  [PROJECT_STATUS.ARCHIVED]: [],
};

module.exports = {
  SYSTEM_ROLES,
  SYSTEM_ROLE_VALUES,
  USER_STATUS,
  USER_STATUS_VALUES,
  APPROVAL_STATUS,
  APPROVAL_STATUS_VALUES,
  AUDIT_ACTIONS,
  PROJECT_STATUS,
  PROJECT_STATUS_VALUES,
  PROJECT_TAGS,
  PROJECT_TAG_VALUES,
  PROJECT_ROLES,
  PROJECT_ROLE_VALUES,
  TASK_STATUS,
  TASK_STATUS_VALUES,
  TASK_PRIORITY,
  TASK_PRIORITY_VALUES,
  REPORT_STATUS,
  REPORT_STATUS_VALUES,
  GIT_PROVIDERS,
  GIT_PROVIDER_VALUES,
  GIT_VISIBILITY,
  GIT_VISIBILITY_VALUES,
  PROJECT_STATUS_TRANSITIONS,
};
